version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bank-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bank-app
      DB_USER: postgres
      DB_PASSWORD: 123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: ["python", "-u", "src/generate_data.py"]

volumes:
  db_data: 